# Generated by Django 4.1.5 on 2023-03-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neona_sports', '0005_remove_contact_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='Contact_us',
        ),
    ]
