# Generated by Django 4.1.5 on 2023-04-02 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neona_sports', '0008_category_main_category_sub_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Main_category',
            new_name='main_category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='neona_sports.category'),
        ),
        migrations.DeleteModel(
            name='sub_category',
        ),
    ]
